package seeder

import (
	"github.com/google/uuid"
	"matchlove-services/internal/model"
	"time"
)

var userProfileComplete = []*model.UserProfile{
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_1",
		ProfilePictureURL: "http://example.com/user1.jpg",
		FirstName:         "John",
		LastName:          "Doe",
		Bio:               "Love outdoor activities.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC),
		Age:               34,
		Height:            180.5,
		Weight:            75.0,
		Zodiac:            "Capricorn",
		BloodType:         "O",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "LT_PARTNER",
		LoveLanguage:      "WORDS_OF_AFFIRMATION",
		City:              "BOGOR",
		Longitude:         106.8032,
		Latitude:          -6.5962,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_2",
		ProfilePictureURL: "http://example.com/user2.jpg",
		FirstName:         "Jane",
		LastName:          "Smith",
		Bio:               "Enjoys painting and music.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1985, 2, 14, 0, 0, 0, 0, time.UTC),
		Age:               39,
		Height:            165.0,
		Weight:            60.0,
		Zodiac:            "Aquarius",
		BloodType:         "A",
		Education:         "Master",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "QUALITY_TIME",
		City:              "BOGOR",
		Longitude:         106.8048,
		Latitude:          -6.5886,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_3",
		ProfilePictureURL: "http://example.com/user3.jpg",
		FirstName:         "Alice",
		LastName:          "Johnson",
		Bio:               "Passionate about technology.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1992, 3, 3, 0, 0, 0, 0, time.UTC),
		Age:               32,
		Height:            170.0,
		Weight:            65.0,
		Zodiac:            "Pisces",
		BloodType:         "B",
		Education:         "PhD",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "ACTS_OF_SERVICE",
		City:              "BOGOR",
		Longitude:         106.8019,
		Latitude:          -6.5999,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_4",
		ProfilePictureURL: "http://example.com/user4.jpg",
		FirstName:         "Bob",
		LastName:          "Williams",
		Bio:               "Avid traveler and foodie.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1988, 4, 25, 0, 0, 0, 0, time.UTC),
		Age:               36,
		Height:            175.0,
		Weight:            70.0,
		Zodiac:            "Taurus",
		BloodType:         "AB",
		Education:         "High School",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8065,
		Latitude:          -6.5973,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_5",
		ProfilePictureURL: "http://example.com/user5.jpg",
		FirstName:         "Charlie",
		LastName:          "Brown",
		Bio:               "Love reading and writing.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1995, 5, 15, 0, 0, 0, 0, time.UTC),
		Age:               29,
		Height:            172.0,
		Weight:            68.0,
		Zodiac:            "Gemini",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "INTROVERT",
		LookingFor:        "LT_PARTNER",
		LoveLanguage:      "PHYSICAL_TOUCH",
		City:              "BOGOR",
		Longitude:         106.8071,
		Latitude:          -6.5918,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_6",
		ProfilePictureURL: "http://example.com/user6.jpg",
		FirstName:         "David",
		LastName:          "Miller",
		Bio:               "Fitness enthusiast.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1987, 6, 20, 0, 0, 0, 0, time.UTC),
		Age:               37,
		Height:            178.0,
		Weight:            73.0,
		Zodiac:            "Cancer",
		BloodType:         "O",
		Education:         "Bachelor",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "QUALITY_TIME",
		City:              "BOGOR",
		Longitude:         106.8028,
		Latitude:          -6.5945,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_7",
		ProfilePictureURL: "http://example.com/user7.jpg",
		FirstName:         "Emily",
		LastName:          "Davis",
		Bio:               "Fashion lover and designer.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1993, 7, 30, 0, 0, 0, 0, time.UTC),
		Age:               31,
		Height:            160.0,
		Weight:            55.0,
		Zodiac:            "Leo",
		BloodType:         "A",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8050,
		Latitude:          -6.5983,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_8",
		ProfilePictureURL: "http://example.com/user8.jpg",
		FirstName:         "Frank",
		LastName:          "Moore",
		Bio:               "Tech geek and gamer.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1990, 8, 18, 0, 0, 0, 0, time.UTC),
		Age:               34,
		Height:            180.0,
		Weight:            75.0,
		Zodiac:            "Virgo",
		BloodType:         "AB",
		Education:         "Master",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "WORDS_OF_AFFIRMATION",
		City:              "BOGOR",
		Longitude:         106.8011,
		Latitude:          -6.5902,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_9",
		ProfilePictureURL: "http://example.com/user9.jpg",
		FirstName:         "Grace",
		LastName:          "Taylor",
		Bio:               "Animal lover and vegan.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1989, 9, 5, 0, 0, 0, 0, time.UTC),
		Age:               35,
		Height:            168.0,
		Weight:            62.0,
		Zodiac:            "Libra",
		BloodType:         "O",
		Education:         "Bachelor",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "ACTS_OF_SERVICE",
		City:              "BOGOR",
		Longitude:         106.8060,
		Latitude:          -6.5931,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_10",
		ProfilePictureURL: "http://example.com/user10.jpg",
		FirstName:         "Hank",
		LastName:          "Anderson",
		Bio:               "Cooking is my passion.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1986, 10, 12, 0, 0, 0, 0, time.UTC),
		Age:               38,
		Height:            182.0,
		Weight:            80.0,
		Zodiac:            "Scorpio",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "LT_PARTNER",
		LoveLanguage:      "PHYSICAL_TOUCH",
		City:              "BOGOR",
		Longitude:         106.8042,
		Latitude:          -6.5986,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_11",
		ProfilePictureURL: "http://example.com/user11.jpg",
		FirstName:         "Ivy",
		LastName:          "Martinez",
		Bio:               "Travel blogger.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1991, 11, 22, 0, 0, 0, 0, time.UTC),
		Age:               33,
		Height:            163.0,
		Weight:            58.0,
		Zodiac:            "Sagittarius",
		BloodType:         "A",
		Education:         "Master",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "QUALITY_TIME",
		City:              "BOGOR",
		Longitude:         106.8024,
		Latitude:          -6.5965,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_12",
		ProfilePictureURL: "http://example.com/user12.jpg",
		FirstName:         "Jack",
		LastName:          "Garcia",
		Bio:               "Love playing guitar.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1984, 12, 3, 0, 0, 0, 0, time.UTC),
		Age:               40,
		Height:            175.0,
		Weight:            70.0,
		Zodiac:            "Sagittarius",
		BloodType:         "AB",
		Education:         "PhD",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "WORDS_OF_AFFIRMATION",
		City:              "BOGOR",
		Longitude:         106.8053,
		Latitude:          -6.5970,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_13",
		ProfilePictureURL: "http://example.com/user13.jpg",
		FirstName:         "Kim",
		LastName:          "Hernandez",
		Bio:               "Yoga instructor.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1996, 1, 14, 0, 0, 0, 0, time.UTC),
		Age:               28,
		Height:            158.0,
		Weight:            54.0,
		Zodiac:            "Capricorn",
		BloodType:         "O",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "ACTS_OF_SERVICE",
		City:              "BOGOR",
		Longitude:         106.8039,
		Latitude:          -6.5938,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_14",
		ProfilePictureURL: "http://example.com/user14.jpg",
		FirstName:         "Leo",
		LastName:          "Kim",
		Bio:               "Professional photographer.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1985, 2, 10, 0, 0, 0, 0, time.UTC),
		Age:               39,
		Height:            172.0,
		Weight:            65.0,
		Zodiac:            "Aquarius",
		BloodType:         "A",
		Education:         "Master",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "QUALITY_TIME",
		City:              "BOGOR",
		Longitude:         106.8027,
		Latitude:          -6.5922,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_15",
		ProfilePictureURL: "http://example.com/user15.jpg",
		FirstName:         "Mia",
		LastName:          "Lopez",
		Bio:               "Fashion model and designer.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1993, 3, 1, 0, 0, 0, 0, time.UTC),
		Age:               31,
		Height:            168.0,
		Weight:            59.0,
		Zodiac:            "Pisces",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "ACTS_OF_SERVICE",
		City:              "BOGOR",
		Longitude:         106.8044,
		Latitude:          -6.5947,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_16",
		ProfilePictureURL: "http://example.com/user16.jpg",
		FirstName:         "Nina",
		LastName:          "Nguyen",
		Bio:               "Artist and sculptor.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1988, 4, 20, 0, 0, 0, 0, time.UTC),
		Age:               36,
		Height:            162.0,
		Weight:            56.0,
		Zodiac:            "Taurus",
		BloodType:         "O",
		Education:         "Master",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8063,
		Latitude:          -6.5960,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_17",
		ProfilePictureURL: "http://example.com/user17.jpg",
		FirstName:         "Oscar",
		LastName:          "Perez",
		Bio:               "Freelance writer.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1992, 5, 8, 0, 0, 0, 0, time.UTC),
		Age:               32,
		Height:            170.0,
		Weight:            67.0,
		Zodiac:            "Gemini",
		BloodType:         "A",
		Education:         "Bachelor",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "WORDS_OF_AFFIRMATION",
		City:              "BOGOR",
		Longitude:         106.8031,
		Latitude:          -6.5932,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_18",
		ProfilePictureURL: "http://example.com/user18.jpg",
		FirstName:         "Paul",
		LastName:          "Reed",
		Bio:               "Music producer.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1986, 6, 19, 0, 0, 0, 0, time.UTC),
		Age:               38,
		Height:            180.0,
		Weight:            75.0,
		Zodiac:            "Cancer",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "QUALITY_TIME",
		City:              "BOGOR",
		Longitude:         106.8070,
		Latitude:          -6.5927,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_19",
		ProfilePictureURL: "http://example.com/user19.jpg",
		FirstName:         "Quinn",
		LastName:          "Robinson",
		Bio:               "Software engineer.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1985, 7, 13, 0, 0, 0, 0, time.UTC),
		Age:               39,
		Height:            178.0,
		Weight:            72.0,
		Zodiac:            "Leo",
		BloodType:         "O",
		Education:         "PhD",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8056,
		Latitude:          -6.5948,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_20",
		ProfilePictureURL: "http://example.com/user20.jpg",
		FirstName:         "Rachel",
		LastName:          "Martinez",
		Bio:               "Marketing specialist.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1993, 8, 24, 0, 0, 0, 0, time.UTC),
		Age:               31,
		Height:            165.0,
		Weight:            60.0,
		Zodiac:            "Virgo",
		BloodType:         "A",
		Education:         "Bachelor",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "WORDS_OF_AFFIRMATION",
		City:              "BOGOR",
		Longitude:         106.8029,
		Latitude:          -6.5982,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_21",
		ProfilePictureURL: "http://example.com/user21.jpg",
		FirstName:         "Steve",
		LastName:          "Young",
		Bio:               "Business analyst.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1990, 9, 1, 0, 0, 0, 0, time.UTC),
		Age:               34,
		Height:            178.0,
		Weight:            74.0,
		Zodiac:            "Libra",
		BloodType:         "AB",
		Education:         "Master",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "ACTS_OF_SERVICE",
		City:              "BOGOR",
		Longitude:         106.8038,
		Latitude:          -6.5919,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_22",
		ProfilePictureURL: "http://example.com/user22.jpg",
		FirstName:         "Tina",
		LastName:          "Hall",
		Bio:               "Graphic designer.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1987, 10, 30, 0, 0, 0, 0, time.UTC),
		Age:               37,
		Height:            160.0,
		Weight:            55.0,
		Zodiac:            "Scorpio",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8061,
		Latitude:          -6.5934,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_23",
		ProfilePictureURL: "http://example.com/user23.jpg",
		FirstName:         "Uma",
		LastName:          "Nelson",
		Bio:               "Nature lover and hiker.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1994, 11, 8, 0, 0, 0, 0, time.UTC),
		Age:               30,
		Height:            162.0,
		Weight:            57.0,
		Zodiac:            "Sagittarius",
		BloodType:         "A",
		Education:         "Master",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "QUALITY_TIME",
		City:              "BOGOR",
		Longitude:         106.8034,
		Latitude:          -6.5917,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_24",
		ProfilePictureURL: "http://example.com/user24.jpg",
		FirstName:         "Victor",
		LastName:          "Gonzalez",
		Bio:               "Love adventure sports.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1989, 12, 22, 0, 0, 0, 0, time.UTC),
		Age:               35,
		Height:            185.0,
		Weight:            80.0,
		Zodiac:            "Capricorn",
		BloodType:         "O",
		Education:         "Bachelor",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "WORDS_OF_AFFIRMATION",
		City:              "BOGOR",
		Longitude:         106.8057,
		Latitude:          -6.5949,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_25",
		ProfilePictureURL: "http://example.com/user25.jpg",
		FirstName:         "Wendy",
		LastName:          "King",
		Bio:               "Baking enthusiast.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1991, 1, 15, 0, 0, 0, 0, time.UTC),
		Age:               33,
		Height:            167.0,
		Weight:            60.0,
		Zodiac:            "Capricorn",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8061,
		Latitude:          -6.5934,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_21",
		ProfilePictureURL: "http://example.com/user21.jpg",
		FirstName:         "Steve",
		LastName:          "Young",
		Bio:               "Business analyst.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1990, 9, 1, 0, 0, 0, 0, time.UTC),
		Age:               34,
		Height:            178.0,
		Weight:            74.0,
		Zodiac:            "Libra",
		BloodType:         "AB",
		Education:         "Master",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "ACTS_OF_SERVICE",
		City:              "BOGOR",
		Longitude:         106.8038,
		Latitude:          -6.5919,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_22",
		ProfilePictureURL: "http://example.com/user22.jpg",
		FirstName:         "Tina",
		LastName:          "Hall",
		Bio:               "Graphic designer.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1987, 10, 30, 0, 0, 0, 0, time.UTC),
		Age:               37,
		Height:            160.0,
		Weight:            55.0,
		Zodiac:            "Scorpio",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8061,
		Latitude:          -6.5934,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_23",
		ProfilePictureURL: "http://example.com/user23.jpg",
		FirstName:         "Uma",
		LastName:          "Nelson",
		Bio:               "Nature lover and hiker.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1994, 11, 8, 0, 0, 0, 0, time.UTC),
		Age:               30,
		Height:            162.0,
		Weight:            57.0,
		Zodiac:            "Sagittarius",
		BloodType:         "A",
		Education:         "Master",
		Personality:       "INTROVERT",
		LookingFor:        "LOOKING_SIBLING",
		LoveLanguage:      "QUALITY_TIME",
		City:              "BOGOR",
		Longitude:         106.8034,
		Latitude:          -6.5917,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_24",
		ProfilePictureURL: "http://example.com/user24.jpg",
		FirstName:         "Victor",
		LastName:          "Gonzalez",
		Bio:               "Love adventure sports.",
		Gender:            "Male",
		DateOfBirth:       time.Date(1989, 12, 22, 0, 0, 0, 0, time.UTC),
		Age:               35,
		Height:            185.0,
		Weight:            80.0,
		Zodiac:            "Capricorn",
		BloodType:         "O",
		Education:         "Bachelor",
		Personality:       "AMBIVERT",
		LookingFor:        "LOOKING_FRIENDS",
		LoveLanguage:      "WORDS_OF_AFFIRMATION",
		City:              "BOGOR",
		Longitude:         106.8057,
		Latitude:          -6.5949,
	},
	{
		Uuid:              uuid.New(),
		AccountUuid:       "account_uuid_25",
		ProfilePictureURL: "http://example.com/user25.jpg",
		FirstName:         "Wendy",
		LastName:          "King",
		Bio:               "Baking enthusiast.",
		Gender:            "Female",
		DateOfBirth:       time.Date(1991, 1, 15, 0, 0, 0, 0, time.UTC),
		Age:               33,
		Height:            167.0,
		Weight:            60.0,
		Zodiac:            "Capricorn",
		BloodType:         "B",
		Education:         "Bachelor",
		Personality:       "EXTROVERT",
		LookingFor:        "FIGURING_IT_OUT",
		LoveLanguage:      "RECEIVING_GIFTS",
		City:              "BOGOR",
		Longitude:         106.8045,
		Latitude:          -6.5949,
	},
}

var userAccountData = []*model.UserAccount{
	{Uuid: uuid.New(), Username: "john_doe", Email: "john.doe@example.com", Password: "hashed_password_1", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "jane_smith", Email: "jane.smith@example.com", Password: "hashed_password_2", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "michael_johnson", Email: "michael.johnson@example.com", Password: "hashed_password_3", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "emily_wilson", Email: "emily.wilson@example.com", Password: "hashed_password_4", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "daniel_brown", Email: "daniel.brown@example.com", Password: "hashed_password_5", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "olivia_davis", Email: "olivia.davis@example.com", Password: "hashed_password_6", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "william_martinez", Email: "william.martinez@example.com", Password: "hashed_password_7", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "sophia_garcia", Email: "sophia.garcia@example.com", Password: "hashed_password_8", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "james_rodriguez", Email: "james.rodriguez@example.com", Password: "hashed_password_9", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "isabella_lopez", Email: "isabella.lopez@example.com", Password: "hashed_password_10", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "liam_hernandez", Email: "liam.hernandez@example.com", Password: "hashed_password_11", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "ava_gonzalez", Email: "ava.gonzalez@example.com", Password: "hashed_password_12", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "noah_perez", Email: "noah.perez@example.com", Password: "hashed_password_13", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "mia_rivera", Email: "mia.rivera@example.com", Password: "hashed_password_14", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "logan_torres", Email: "logan.torres@example.com", Password: "hashed_password_15", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "amelia_ramirez", Email: "amelia.ramirez@example.com", Password: "hashed_password_16", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "ethan_flores", Email: "ethan.flores@example.com", Password: "hashed_password_17", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "ella_sanchez", Email: "ella.sanchez@example.com", Password: "hashed_password_18", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "alexander_nguyen", Email: "alexander.nguyen@example.com", Password: "hashed_password_19", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "charlotte_kim", Email: "charlotte.kim@example.com", Password: "hashed_password_20", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user1", Email: "user1@example.com", Password: "password1", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user2", Email: "user2@example.com", Password: "password2", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user3", Email: "user3@example.com", Password: "password3", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user4", Email: "user4@example.com", Password: "password4", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user5", Email: "user5@example.com", Password: "password5", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user6", Email: "user6@example.com", Password: "password6", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user7", Email: "user7@example.com", Password: "password7", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user8", Email: "user8@example.com", Password: "password8", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user9", Email: "user9@example.com", Password: "password9", IsCompleteProfile: 1},
	{Uuid: uuid.New(), Username: "user10", Email: "user10@example.com", Password: "password10", IsCompleteProfile: 1},
}

var userProfileData = []*model.UserProfile{
	{Uuid: uuid.New(), AccountUuid: "account_uuid_1", FirstName: "John", LastName: "Doe", Gender: "Male", DateOfBirth: time.Date(1990, time.January, 1, 0, 0, 0, 0, time.UTC), Bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", ProfilePictureURL: "https://example.com/profile1.jpg", Longitude: 106.7985, Latitude: -6.6091},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_2", FirstName: "Jane", LastName: "Smith", Gender: "Female", DateOfBirth: time.Date(1995, time.March, 15, 0, 0, 0, 0, time.UTC), Bio: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.", ProfilePictureURL: "https://example.com/profile2.jpg", Longitude: 106.7973, Latitude: -6.5950},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_3", FirstName: "Michael", LastName: "Johnson", Gender: "Male", DateOfBirth: time.Date(1985, time.August, 10, 0, 0, 0, 0, time.UTC), Bio: "Phasellus vestibulum quam id pretium semper. Sed efficitur ultrices arcu, id finibus libero blandit ac.", ProfilePictureURL: "https://example.com/profile3.jpg", Longitude: 106.7961, Latitude: -6.6053},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_4", FirstName: "Emily", LastName: "Wilson", Gender: "Female", DateOfBirth: time.Date(1992, time.May, 25, 0, 0, 0, 0, time.UTC), Bio: "Nulla facilisi. Aenean posuere augue vel felis dignissim, et bibendum nisl tincidunt.", ProfilePictureURL: "https://example.com/profile4.jpg", Longitude: 106.7997, Latitude: -6.6078},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_5", FirstName: "Daniel", LastName: "Brown", Gender: "Male", DateOfBirth: time.Date(1988, time.February, 3, 0, 0, 0, 0, time.UTC), Bio: "Curabitur convallis eget velit in fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.", ProfilePictureURL: "https://example.com/profile5.jpg", Longitude: 106.7942, Latitude: -6.6021},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_6", FirstName: "Olivia", LastName: "Davis", Gender: "Female", DateOfBirth: time.Date(1991, time.October, 12, 0, 0, 0, 0, time.UTC), Bio: "Maecenas consectetur ipsum quis eros varius, non tincidunt risus pellentesque.", ProfilePictureURL: "https://example.com/profile6.jpg", Longitude: 106.8009, Latitude: -6.6015},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_7", FirstName: "William", LastName: "Martinez", Gender: "Male", DateOfBirth: time.Date(1987, time.July, 18, 0, 0, 0, 0, time.UTC), Bio: "Vestibulum mollis tempor justo, vitae pellentesque magna dictum eget.", ProfilePictureURL: "https://example.com/profile7.jpg", Longitude: 106.7980, Latitude: -6.6105},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_8", FirstName: "Sophia", LastName: "Garcia", Gender: "Female", DateOfBirth: time.Date(1993, time.January, 5, 0, 0, 0, 0, time.UTC), Bio: "Fusce tincidunt odio id ligula euismod, in fermentum elit tristique.", ProfilePictureURL: "https://example.com/profile8.jpg", Longitude: 106.7968, Latitude: -6.6039},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_9", FirstName: "James", LastName: "Rodriguez", Gender: "Male", DateOfBirth: time.Date(1984, time.December, 8, 0, 0, 0, 0, time.UTC), Bio: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", ProfilePictureURL: "https://example.com/profile9.jpg", Longitude: 106.7979, Latitude: -6.6083},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_10", FirstName: "Isabella", LastName: "Lopez", Gender: "Female", DateOfBirth: time.Date(1990, time.April, 20, 0, 0, 0, 0, time.UTC), Bio: "Integer at urna at elit convallis congue.", ProfilePictureURL: "https://example.com/profile10.jpg", Longitude: 106.7953, Latitude: -6.6067},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_11", FirstName: "Liam", LastName: "Hernandez", Gender: "Male", DateOfBirth: time.Date(1989, time.November, 11, 0, 0, 0, 0, time.UTC), Bio: "Vivamus vitae dolor nec nisl lobortis luctus eget id felis.", ProfilePictureURL: "https://example.com/profile11.jpg", Longitude: 106.7991, Latitude: -6.6045},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_12", FirstName: "Ava", LastName: "Gonzalez", Gender: "Female", DateOfBirth: time.Date(1994, time.February, 28, 0, 0, 0, 0, time.UTC), Bio: "Morbi lobortis purus ac nisi suscipit, a malesuada lorem congue.", ProfilePictureURL: "https://example.com/profile12.jpg", Longitude: 106.7966, Latitude: -6.6004},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_13", FirstName: "Noah", LastName: "Perez", Gender: "Male", DateOfBirth: time.Date(1986, time.September, 9, 0, 0, 0, 0, time.UTC), Bio: "Donec maximus ipsum vitae ante lacinia, nec rhoncus velit interdum.", ProfilePictureURL: "https://example.com/profile13.jpg", Longitude: 106.7987, Latitude: -6.6073},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_14", FirstName: "Mia", LastName: "Rivera", Gender: "Female", DateOfBirth: time.Date(1996, time.July, 7, 0, 0, 0, 0, time.UTC), Bio: "Suspendisse sit amet ipsum euismod, iaculis felis in, dictum risus.", ProfilePictureURL: "https://example.com/profile14.jpg", Longitude: 106.7949, Latitude: -6.6089},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_15", FirstName: "Logan", LastName: "Torres", Gender: "Male", DateOfBirth: time.Date(1983, time.March, 22, 0, 0, 0, 0, time.UTC), Bio: "Nam vel orci ac metus tincidunt ullamcorper.", ProfilePictureURL: "https://example.com/profile15.jpg", Longitude: 106.7972, Latitude: -6.6031},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_16", FirstName: "Amelia", LastName: "Ramirez", Gender: "Female", DateOfBirth: time.Date(1997, time.August, 14, 0, 0, 0, 0, time.UTC), Bio: "Phasellus auctor elit quis quam lacinia, et tincidunt velit varius.", ProfilePictureURL: "https://example.com/profile16.jpg", Longitude: 106.7995, Latitude: -6.6060},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_17", FirstName: "Ethan", LastName: "Flores", Gender: "Male", DateOfBirth: time.Date(1982, time.October, 17, 0, 0, 0, 0, time.UTC), Bio: "Quisque non ligula a justo vestibulum fermentum eget vel nunc.", ProfilePictureURL: "https://example.com/profile17.jpg", Longitude: 106.7958, Latitude: -6.6042},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_18", FirstName: "Ella", LastName: "Sanchez", Gender: "Female", DateOfBirth: time.Date(1998, time.December, 30, 0, 0, 0, 0, time.UTC), Bio: "Aliquam erat volutpat. Sed quis dolor a ante egestas consequat.", ProfilePictureURL: "https://example.com/profile18.jpg", Longitude: 106.7982, Latitude: -6.6070},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_19", FirstName: "Alexander", LastName: "Nguyen", Gender: "Male", DateOfBirth: time.Date(1981, time.January, 9, 0, 0, 0, 0, time.UTC), Bio: "Cras condimentum urna et felis lobortis, at maximus libero sollicitudin.", ProfilePictureURL: "https://example.com/profile19.jpg", Longitude: 106.7970, Latitude: -6.6025},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_20", FirstName: "Charlotte", LastName: "Kim", Gender: "Female", DateOfBirth: time.Date(1999, time.June, 5, 0, 0, 0, 0, time.UTC), Bio: "Integer vitae turpis sed ex feugiat luctus sit amet nec ligula.", ProfilePictureURL: "https://example.com/profile20.jpg", Longitude: 106.7963, Latitude: -6.6099},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "John", LastName: "Doe", Gender: "Male", DateOfBirth: time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC), Bio: "Love outdoor activities.", ProfilePictureURL: "http://example.com/user1.jpg", Longitude: 106.6894, Latitude: -6.5963},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Jane", LastName: "Doe", Gender: "Female", DateOfBirth: time.Date(1989, 2, 2, 0, 0, 0, 0, time.UTC), Bio: "Avid reader.", ProfilePictureURL: "http://example.com/user2.jpg", Longitude: 106.7015, Latitude: -6.5856},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Jim", LastName: "Beam", Gender: "Male", DateOfBirth: time.Date(1985, 3, 3, 0, 0, 0, 0, time.UTC), Bio: "Music lover.", ProfilePictureURL: "http://example.com/user3.jpg", Longitude: 106.7142, Latitude: -6.5748},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Jake", LastName: "Smith", Gender: "Male", DateOfBirth: time.Date(1992, 4, 4, 0, 0, 0, 0, time.UTC), Bio: "Tech enthusiast.", ProfilePictureURL: "http://example.com/user4.jpg", Longitude: 106.6831, Latitude: -6.6037},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Jill", LastName: "Johnson", Gender: "Female", DateOfBirth: time.Date(1988, 5, 5, 0, 0, 0, 0, time.UTC), Bio: "Foodie.", ProfilePictureURL: "http://example.com/user5.jpg", Longitude: 106.6948, Latitude: -6.6108},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Jerry", LastName: "Lewis", Gender: "Male", DateOfBirth: time.Date(1991, 6, 6, 0, 0, 0, 0, time.UTC), Bio: "Outdoor enthusiast.", ProfilePictureURL: "http://example.com/user6.jpg", Longitude: 106.7075, Latitude: -6.5992},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Jenny", LastName: "Lee", Gender: "Female", DateOfBirth: time.Date(1987, 7, 7, 0, 0, 0, 0, time.UTC), Bio: "Fashion lover.", ProfilePictureURL: "http://example.com/user7.jpg", Longitude: 106.6712, Latitude: -6.5885},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Jack", LastName: "Brown", Gender: "Male", DateOfBirth: time.Date(1993, 8, 8, 0, 0, 0, 0, time.UTC), Bio: "Gamer.", ProfilePictureURL: "http://example.com/user8.jpg", Longitude: 106.6839, Latitude: -6.5772},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Josie", LastName: "Williams", Gender: "Female", DateOfBirth: time.Date(1986, 9, 9, 0, 0, 0, 0, time.UTC), Bio: "Art lover.", ProfilePictureURL: "http://example.com/user9.jpg", Longitude: 106.6966, Latitude: -6.5661},
	{Uuid: uuid.New(), AccountUuid: "", FirstName: "Joe", LastName: "Davis", Gender: "Male", DateOfBirth: time.Date(1994, 10, 10, 0, 0, 0, 0, time.UTC), Bio: "Traveler.", ProfilePictureURL: "http://example.com/user10.jpg", Longitude: 106.7081, Latitude: -6.5547},
}

var userPreferenceData = []*model.UserPreference{
	{Uuid: uuid.New(), AccountUuid: "account_uuid_1", PreferredGender: "Female", AgeMin: 25, AgeMax: 35, InterestFor: "FITNESS", LookingFor: "LT_PARTNER", Distance: 10.5},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_2", PreferredGender: "Male", AgeMin: 30, AgeMax: 40, InterestFor: "COOKING", LookingFor: "LOOKING_FRIENDS", Distance: 15.0},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_3", PreferredGender: "Female", AgeMin: 28, AgeMax: 38, InterestFor: "OUTDOOR_ADVENTURES", LookingFor: "LOOKING_SIBLING", Distance: 12.0},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_4", PreferredGender: "Male", AgeMin: 27, AgeMax: 37, InterestFor: "MOVIES", LookingFor: "FIGURING_IT_OUT", Distance: 11.0},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_5", PreferredGender: "Female", AgeMin: 26, AgeMax: 36, InterestFor: "OUTDOOR_ADVENTURES", LookingFor: "LT_PARTNER", Distance: 13.0},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_6", PreferredGender: "Male", AgeMin: 32, AgeMax: 42, InterestFor: "ADVENTURE", LookingFor: "LOOKING_FRIENDS", Distance: 16.0},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_7", PreferredGender: "Female", AgeMin: 30, AgeMax: 40, InterestFor: "TRAVELING", LookingFor: "LOOKING_SIBLING", Distance: 14.0},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_8", PreferredGender: "Male", AgeMin: 29, AgeMax: 39, InterestFor: "FITNESS", LookingFor: "FIGURING_IT_OUT", Distance: 12.5},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_9", PreferredGender: "Female", AgeMin: 24, AgeMax: 34, InterestFor: "ART", LookingFor: "LT_PARTNER", Distance: 11.5},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_10", PreferredGender: "Male", AgeMin: 28, AgeMax: 38, InterestFor: "MUSIC_SPOTIFY", LookingFor: "LOOKING_FRIENDS", Distance: 15.5},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_11", PreferredGender: "Female", AgeMin: 26, AgeMax: 36, InterestFor: "READING", LookingFor: "LOOKING_SIBLING", Distance: 13.5},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_12", PreferredGender: "Male", AgeMin: 31, AgeMax: 41, InterestFor: "TECHNOLOGY", LookingFor: "FIGURING_IT_OUT", Distance: 17.0},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_13", PreferredGender: "Female", AgeMin: 29, AgeMax: 39, InterestFor: "FOODIE", LookingFor: "LT_PARTNER", Distance: 14.5},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_14", PreferredGender: "Male", AgeMin: 25, AgeMax: 35, InterestFor: "MOVIES", LookingFor: "LOOKING_FRIENDS", Distance: 12.8},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_15", PreferredGender: "Female", AgeMin: 27, AgeMax: 37, InterestFor: "GAMING", LookingFor: "LOOKING_SIBLING", Distance: 11.8},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_16", PreferredGender: "Male", AgeMin: 30, AgeMax: 40, InterestFor: "SPORTS", LookingFor: "FIGURING_IT_OUT", Distance: 13.8},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_17", PreferredGender: "Female", AgeMin: 28, AgeMax: 38, InterestFor: "PETS", LookingFor: "LT_PARTNER", Distance: 15.2},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_18", PreferredGender: "Male", AgeMin: 26, AgeMax: 36, InterestFor: "NATURE", LookingFor: "LOOKING_FRIENDS", Distance: 16.5},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_19", PreferredGender: "Female", AgeMin: 30, AgeMax: 40, InterestFor: "FASHION", LookingFor: "LOOKING_SIBLING", Distance: 14.7},
	{Uuid: uuid.New(), AccountUuid: "account_uuid_20", PreferredGender: "Male", AgeMin: 27, AgeMax: 37, InterestFor: "HISTORY", LookingFor: "FIGURING_IT_OUT", Distance: 12.3},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Female", AgeMin: 25, AgeMax: 35, InterestFor: "FITNESS", LookingFor: "LT_PARTNER", Distance: 4.5},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Male", AgeMin: 30, AgeMax: 40, InterestFor: "COOKING", LookingFor: "LOOKING_FRIENDS", Distance: 3.0},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Female", AgeMin: 28, AgeMax: 38, InterestFor: "OUTDOOR_ADVENTURES", LookingFor: "LOOKING_SIBLING", Distance: 4.0},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Male", AgeMin: 27, AgeMax: 37, InterestFor: "MOVIES", LookingFor: "FIGURING_IT_OUT", Distance: 4.5},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Female", AgeMin: 26, AgeMax: 36, InterestFor: "OUTDOOR_ADVENTURES", LookingFor: "LT_PARTNER", Distance: 4.0},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Male", AgeMin: 32, AgeMax: 42, InterestFor: "TRAVELING", LookingFor: "LOOKING_FRIENDS", Distance: 3.5},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Female", AgeMin: 30, AgeMax: 40, InterestFor: "TRAVELING", LookingFor: "LOOKING_SIBLING", Distance: 4.5},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Male", AgeMin: 29, AgeMax: 39, InterestFor: "FITNESS", LookingFor: "FIGURING_IT_OUT", Distance: 4.0},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Female", AgeMin: 24, AgeMax: 34, InterestFor: "ART", LookingFor: "LT_PARTNER", Distance: 3.5},
	{Uuid: uuid.New(), AccountUuid: "AccountUuid", PreferredGender: "Male", AgeMin: 28, AgeMax: 38, InterestFor: "MUSIC_SPOTIFY", LookingFor: "LOOKING_FRIENDS", Distance: 4.0},
}
