SERVER_PORT: 8000

ACCESS_TOKEN_SECRET: "sampelscrettoken"
REFRESH_TOKEN_SECRET: "sampelscrettoken"

DB_DSN: "serverhostdb:dbpass@tcp(dbusername:dbport)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
